name: 'DTS Rebuild Action'
description: 'Rebuilds static DTS collection file after every commit.'
inputs:
  owner:
    description: 'The owner of the repository'
    required: true
  repo:
    description: 'The name of the repository'
    required: true
  token:
    description: 'The token to use to access the GitHub API'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'